apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-pod
  template:
    metadata:
      labels:
        app: client-pod
    spec:
      containers:
        - name: space-client
          image: space-api-space-client
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: client-config
      restartPolicy: Always
