apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server-service
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: server-pod
  type: ClusterIP