apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: space-statics
  name: space-statics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
